title: Zhijie Wang
author: Zhijie Wang
#remote_theme: riggraz/no-style-please
remote_theme: ritijjain/pudhina-fresh
description: Zhiije Wang's Homepage

#theme_config:
#  appearance: "light"
#  back_home_text: ".." # customize text for homepage link in post layout
#  date_format: "%Y-%m-%d" # customize how date is formatted
#  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
