title: Zhijie Wang
author: Zhijie Wang
#description: Zhiije Wang's Homepage

#show_downloads: false
#theme: jekyll-theme-cayman
remote_theme: rahul-bothra/parchment 

#github:
#  home: /
#  cv: /cv
#  publications: /publications
    
#sass:
#  style: :compressed

#plugins:
#  - jekyll-seo-tag
