title: Zhijie Wang
author: Zhijie Wang
baseurl: "/zhijiew.github.io"

markdown: kramdown

nav:
 - name: "About"
   link: "about"
 - name: "Resume"
   link: "cv"
 - name: "Publications"
   link: "publications"
    
sass:
  style: compressed
  sass_dir: _sass
